
language: generic
dist: bionic
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

before_install:
   - wget -c https://files.seeedstudio.com/arduino/seeed-arduino-ci.sh

script:
   - chmod +x seeed-arduino-ci.sh
   - cat $PWD/seeed-arduino-ci.sh
   - bash $PWD/seeed-arduino-ci.sh new_firmware:uno/new_firmware:servo:seeed_XIAO_m0/UpdateFrimware:uno/UpdateFrimware:servo:seeed_XIAO_m0/ReadSensorValue_Xadow:uno/ReadSensorValue_Xadow:servo:seeed_XIAO_m0

notifications:
  email:
    on_success: change
    on_failure: change
